name: Android APK Build from Zip

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Unzip Project Files
      run: unzip idle-rpg-project.zip

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant Permission to gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK file
      uses: actions/upload-artifact@v4
      with:
        name: idle-rpg-apk
        path: app/build/outputs/apk/debug/app-debug.apk
